### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by miron-khoruzhenko** [miron-khoruzhenko/vite-portfolio#1]
- [ ] Изменить иконку сайта и название
- [ ] Сделать иконки для всех платформ
- [ ] Контактная форма не работает
- [ ] Заполнить карусели с проектами (картинки, текст, ссылки)
- [ ] Заполнить сайт текстом
- [ ] Добавить Loader для закрузки картинок
- [ ] Добавить RouteGuard для показухи
- [ ] Возможность скачивать CV
- [ ] Заполнить секту Portfolio на About Me
